# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli" do
  name "swarmcli"
  desc "Docker Swarm TUI management tool"
  homepage "https://swarmcli.io"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "c023eabc9039d9eca6e3b21e31b6a648356fb56157480381dc60bd2b22befa5c"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "1aae97b585cfa18dcb2b2a99122f06bad6d737b11adb6cd961ab6c102450861e"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "6cc22e952bb348d631ae6d5e4d29bfc18b2219e5ef4f6e7b251b61553dd59019"
    end
  end

  conflicts_with cask: [
      "swarmcli-be",
      "swarmcli-oss",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
