# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-be" do
  name "swarmcli-be"
  desc "Docker Swarm TUI management tool (Business Edition)"
  homepage "https://swarmcli.io"
  version "1.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "240f2c26ab8938be161af501382a73e9436b0b0db159a3398c0a2971fbf2f969"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "db1455c03f73d791d1b24eb0c5df871fec86502486c790202513e05f7cb066aa"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "3d4ed64e4c54646e1b94c38c3d8fadaff8245309a2d7c1a41cb4d775f24cdba0"
    end
  end

  conflicts_with cask: [
      "swarmcli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
