# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-be" do
  name "swarmcli-be"
  desc "Docker Swarm TUI management tool (Business Edition)"
  homepage "https://swarmcli.io"
  version "1.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "7abddb67907ea317a3b29e9bc4b3da03bd1d6f8d9ddf1b4526a12660df85c9c6"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "85eb6bff9ccbaf621c32f0ab2fe2b96fd189cf60076cc1704dbdbd4b73f9ebd3"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "51dd0ed86dae832d62127754e9f9925109ce863dc1c23ffa717a128b1436d9cf"
    end
  end

  conflicts_with cask: [
      "swarmcli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
