# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli" do
  name "swarmcli"
  desc "Docker Swarm TUI management tool"
  homepage "https://swarmcli.io"
  version "1.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "5909ffeeec061541aa26472033f3909900af106d6baf76f9086f6acfc48a4948"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "0beeca4cc08daa284e29acda5984c33ac363e63cdd0c268d010a68b75bdffa74"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "07839126533feac0c05dc4bc8a03c8ee2c74dec9e17646333755903eedfe8401"
    end
  end

  conflicts_with cask: [
      "swarmcli-be",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
