# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-be" do
  deprecate! date: "2026-08-07", because: "has been renamed to `swarmcli`, which installs the same build"

  name "swarmcli-be"
  desc "Docker Swarm TUI management tool (deprecated: install swarmcli)"
  homepage "https://swarmcli.io"
  version "1.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "4c89b50c159ffa00c3685226e0fb0190994489ecfbd9898846302a6b244f816e"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "b410cb41bdd7066058c6348a1c08a57063a971f87220987bcfe084b977077487"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "f45bf434c499b22afbb93149bfdd02cd0bea949e05ec6cafff34961c69508702"
    end
  end

  conflicts_with cask: [
      "swarmcli",
      "swarmcli-oss",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  caveats do
    "swarmcli-be has been renamed. This cask installs the same build as"
    "`swarmcli`; switch with:"
    ""
    "  brew uninstall --cask swarmcli-be && brew install swarmcli"
  end

  # No zap stanza required
end
