# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli" do
  name "swarmcli"
  desc "Docker Swarm TUI management tool"
  homepage "https://swarmcli.io"
  version "1.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all.tar.gz"
    sha256 "0b3ee4da693b2aaa694c66b4ba94e5c100b1208c1dc0d0445604e44cf87c99ac"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64.tar.gz"
      sha256 "ce7ee27e6d68a188b28427d063004b38f8e32d1be59320e96bc57f3831037494"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64.tar.gz"
      sha256 "4c48338c6826f53d83ab702aadfee80621be9c4c7d7840b5a2a47b479a8b1a81"
    end
  end

  conflicts_with cask: [
      "swarmcli-be",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
