# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-oss" do
  name "swarmcli-oss"
  desc "Docker Swarm TUI management tool (Apache-2.0 build)"
  homepage "https://swarmcli.io"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all_oss.tar.gz"
    sha256 "dc73fabae7b349c1fc5399aed8a7d75f233943e95f24ba9280303d3425225d20"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64_oss.tar.gz"
      sha256 "56f6def2c1a34ab0d854cd7df5a0b684fb74b07b283a78980625f13078770e7f"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64_oss.tar.gz"
      sha256 "470183866f76bddfc9a9c7435aebc79ca8850ae949623e4cd7205405722a0a05"
    end
  end

  conflicts_with cask: [
      "swarmcli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
