# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-oss" do
  name "swarmcli-oss"
  desc "Docker Swarm TUI management tool (Apache-2.0 build)"
  homepage "https://swarmcli.io"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all_oss.tar.gz"
    sha256 "c3ab9db8e466c11cfef16126a9278b5563ec08d9d612c354b8708b8364245852"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64_oss.tar.gz"
      sha256 "f750a4031eb6be82ae4419239da3c215bd9e2b82b34ec9b42106ac87bc77bd1b"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64_oss.tar.gz"
      sha256 "623c05a4e50474117fcb9feaf973f0d2bf3257294a8f51f8b26cd0dc7c2d89c6"
    end
  end

  conflicts_with cask: [
      "swarmcli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
