# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarmcli-oss" do
  name "swarmcli-oss"
  desc "Docker Swarm TUI management tool (Apache-2.0 build)"
  homepage "https://swarmcli.io"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarmcli"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Darwin_all_oss.tar.gz"
    sha256 "1a8fe7d02796650c588b98dd71ccc06cd6b26dcdb10f89cf2916eec2e6c03ca1"
  end

  on_linux do
    on_intel do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_x86_64_oss.tar.gz"
      sha256 "dd4df3a8fe6d590867c32a2b5cfc52cf3d7321962a52ceba45352992e64766dc"
    end
    on_arm do
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v#{version}/swarmcli_Linux_arm64_oss.tar.gz"
      sha256 "06ba27467b35426f659b4a97eca015a149b2a875410a54f7ef60933df2f559cc"
    end
  end

  conflicts_with cask: [
      "swarmcli",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarmcli"]
    end
  end

  # No zap stanza required
end
