# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarmcli < Formula
  desc "Docker Swarm TUI management tool"
  homepage "https://swarmcli.io"
  version "1.6.0-rc2"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.6.0-rc2/swarmcli_Darwin_all.tar.gz"
    sha256 "21ab788a68181e0469ec3d3a11b4c580472efea3992389d991e2e6dbc13167cb"

    define_method(:install) do
      bin.install "swarmcli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.6.0-rc2/swarmcli_Linux_x86_64.tar.gz"
      sha256 "e9ff2865065c6f438f8846c88e97a909fafca90cde58064975e1b40fdba912b5"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.6.0-rc2/swarmcli_Linux_armv6.tar.gz"
      sha256 "ee0d5e5a4dc50c45cd9aa4f4091dc96df838d8b8e5b26935c7f1b2e98a171b29"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.6.0-rc2/swarmcli_Linux_arm64.tar.gz"
      sha256 "06bc623ef7047d657be9ca2d4b4213a874c18b5bc164e8a545a7ca3abe75d30b"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
  end
end
