# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarmcli < Formula
  desc "Docker Swarm TUI management tool"
  homepage "https://swarmcli.io"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.3.1/swarmcli_Darwin_all.tar.gz"
    sha256 "39c57afcb2f576c0b40f9bf3edad40417b633689e9b9587adcfb2d5507686d3d"

    def install
      bin.install "swarmcli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.3.1/swarmcli_Linux_x86_64.tar.gz"
      sha256 "03345c9a103a96327969f690d92b9ad95364c23f97ebdbcbcbaefbd02ff60fcb"
      def install
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.3.1/swarmcli_Linux_armv6.tar.gz"
      sha256 "6d39f639f37eef7d0bac3b99019e3640f11692f3c4972957f11e490991793d3a"
      def install
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli/releases/download/v1.3.1/swarmcli_Linux_arm64.tar.gz"
      sha256 "9dbe8c47452008cc98728b5858d5df3dd373445f9db087bd27fd59cfcd613280"
      def install
        bin.install "swarmcli"
      end
    end
  end
end
