# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SwarmcliBe < Formula
  desc "Docker Swarm TUI management tool (Business Edition)"
  homepage "https://swarmcli.io"
  version "1.0.0-rc6"

  on_macos do
    url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v1.0.0-rc6/swarmcli_Darwin_all.tar.gz"
    sha256 "421d0518a4e108e7a53fc99ed3e99fd3af81866be7b0b30b0e1a8eb2c30e84e9"

    define_method(:install) do
      bin.install "swarmcli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v1.0.0-rc6/swarmcli_Linux_x86_64.tar.gz"
      sha256 "828456b1f08e120fba4d0183e6a8d2f40750c77695050a4595650f938da72a21"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v1.0.0-rc6/swarmcli_Linux_armv6.tar.gz"
      sha256 "453c891ec82ff189df3d7d05ce25c4ab1f06621605a45c8002dd8ccf31e59590"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eldara-Tech/swarmcli-be-releases/releases/download/v1.0.0-rc6/swarmcli_Linux_arm64.tar.gz"
      sha256 "46540e6996b7254175bb246ea217d53ae3fb624bfd89d60f871de822e729435e"
      define_method(:install) do
        bin.install "swarmcli"
      end
    end
  end

  conflicts_with "swarmcli"
end
